name=input("Enter Your Name : ")
age=int(input("Enter Your Age : "))
city=input("Enter Your City : ")
print(f"Hello, {name}! Your are {age} years old.")
print(f"You are from {city}.")
print("Git fetch practice")
print("PR Practice")
